# Generated by Django 4.2.13 on 2024-05-30 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('notebook', 'Jupyter Notebook'), ('pdf', 'PDF')], default='html', max_length=20)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/projects')),
                ('featured_image', models.ImageField(upload_to='images/projects/featured/')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured project')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('published_on', models.DateField(verbose_name='Publish date')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_on', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email is verified')),
            ],
            options={
                'verbose_name': 'Subscriber',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Skill')),
                ('image', models.ImageField(null=True, upload_to='images/skills/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(related_name='skills', to='core.projectportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service')),
                ('description', tinymce.models.HTMLField()),
                ('featured', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(related_name='services', to='core.projectportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='SectionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('value_type', models.CharField(choices=[('html', 'HTML'), ('image', 'Image')], default='html', max_length=10)),
                ('html_value', tinymce.models.HTMLField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('email', 'Email'), ('phone', 'Phone number'), ('url', 'URL'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10)),
                ('text_value', models.CharField(blank=True, max_length=100, null=True)),
                ('html_value', tinymce.models.HTMLField(blank=True, null=True)),
                ('email_value', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_value', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid phone number like +12125552368', max_length=128, null=True, region=None)),
                ('url_value', models.URLField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file_value', models.FileField(blank=True, null=True, upload_to='files/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.configurationsetting')),
            ],
        ),
    ]
