# Generated by Django 5.0.6 on 2024-05-09 05:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectportfolio',
            name='body',
        ),
        migrations.RemoveField(
            model_name='projectportfolio',
            name='desscription',
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
