# Generated by Django 5.0.6 on 2024-05-09 05:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projectportfolio_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectportfolio',
            name='description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
