# Generated by Django 5.0.6 on 2024-05-09 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projectportfolio_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectportfolio',
            name='publish',
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured project'),
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 5, 23, 57, 19640, tzinfo=datetime.timezone.utc), verbose_name='Publish date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectportfolio',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
