# Generated by Django 5.0.6 on 2024-05-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_projectportfolio_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='published_on',
            field=models.DateField(verbose_name='Publish date'),
        ),
    ]
