# Generated by Django 5.0.6 on 2024-05-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projectportfolio_published_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='project',
            new_name='projects',
        ),
    ]
