# Generated by Django 5.0.6 on 2024-05-09 09:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_project_skill_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service')),
                ('description', tinymce.models.HTMLField()),
                ('featured', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(related_name='services', to='core.projectportfolio')),
            ],
        ),
    ]
