# Generated by Django 5.0.6 on 2024-05-09 11:10

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', tinymce.models.HTMLField()),
                ('about_image', models.ImageField(upload_to='configurations/')),
                ('logo', models.ImageField(upload_to='configurations/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('website_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('github_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('twitter_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('facebook_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('instagram_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('whatsapp_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
