# Generated by Django 5.0.6 on 2024-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configurationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsetting',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
