# Generated by Django 5.0.6 on 2024-05-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_configurationsetting_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationsetting',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='configurationsetting',
            name='object_id',
        ),
    ]
