# Generated by Django 5.0.6 on 2024-05-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_configurationsetting_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationsetting',
            name='integer_value',
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
