# Generated by Django 5.0.6 on 2024-05-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_configurationsetting_integer_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configurations',
        ),
    ]
