# Generated by Django 5.0.6 on 2024-05-10 08:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsetting',
            name='email_value',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configurationsetting',
            name='phone_value',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid phone number like +12125552368', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone number'), ('url', 'URL'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
