# Generated by Django 5.0.6 on 2024-05-10 08:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configurationsetting_email_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsetting',
            name='html_value',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('email', 'Email'), ('phone', 'Phone number'), ('url', 'URL'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
