# Generated by Django 5.0.6 on 2024-05-10 11:16

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configurationsetting_html_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsetting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationsetting',
            name='text_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('email', 'Email'), ('phone', 'Phone number'), ('url', 'URL'), ('image', 'Image'), ('file', 'File')], default='html', max_length=10)),
                ('html_value', tinymce.models.HTMLField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='core.section')),
            ],
        ),
    ]
