# Generated by Django 4.2.13 on 2024-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_projectportfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
