# Generated by Django 5.0.6 on 2024-05-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
